version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: aurum_solar
      POSTGRES_USER: aurum_user
      POSTGRES_PASSWORD: aurum_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aurum_user -d aurum_solar"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aurum Solar Backend
  backend:
    build: .
    environment:
      DATABASE_URL: postgresql://aurum_user:aurum_password@postgres:5432/aurum_solar
      DATABASE_URL_ASYNC: postgresql+asyncpg://aurum_user:aurum_password@postgres:5432/aurum_solar
      REDIS_URL: redis://redis:6379/0
      DEBUG: "False"
      ENVIRONMENT: production
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
